Algoritmo "faca_para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Leonardo Vieira Guimarães 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/05/2023
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para numero de 100 ate 1 passo -1 faca
        escreval(numero)
   fimpara

Fimalgoritmo